# Generated by Django 4.1.3 on 2022-12-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='backimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
