# Generated by Django 4.1.3 on 2022-12-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendoradd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=100)),
                ('vendoraddress', models.CharField(max_length=200)),
                ('vednorcontactno', models.IntegerField()),
                ('vendoremail', models.EmailField(max_length=254)),
                ('vendorimage', models.ImageField(blank=True, upload_to='vendorimages')),
                ('vendorgistn', models.CharField(max_length=50)),
            ],
        ),
    ]
